name: 'deploy'


on:
  push:
    branches:
      - main
# when made public
# dokku git:sync --build tdash https://github.com/ryanstoner1/dash_test.git main
# dokku git:sync --build coast https://github.com/ryanstoner1/dash_test.git deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          dokku git:sync --build coast ssh://git@github.com/ryanstoner1/dash_test.git deploy
