name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
# when made public
# dokku git:sync --build tdash https://github.com/ryanstoner1/dash_test.git main
# dokku git:sync --build coast https://github.com/ryanstoner1/dash_test.git deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          dokku git:sync --build coast ssh://git@github.com/ryanstoner1/dash_test.git deploy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
